### ISSUE TITLE
SparseKPCovR not returning the proper prediction of the targets

### ISSUE THREAD

**Issue by cbenmahm** [cosmo-epfl/kernel-tutorials#4]
Hello!

I have been looking into `SparseKPCovR` from the Utility Class. 

1) It seems that the predicted targets are missing the average of the training set, i.e the correct prediction of "y" should be "y_pred -> y_pred + Y_train.mean(axis=0)". I can't think of why this is happening from looking at the code.

2) I noticed that in the 4th notebook, the correlation matrix `C_pca` is normalized. However, this is not the case in the Utility Class.

**Comment by ceriottm** [comment]
Now I see. The problem is that if you center the features (or the kernel) you cannot predict a non-zero mean. So when centering one needs to be consistent and also center/standardise the target. This definitely needs better explanation/documentation.
